### ISSUE TITLE
Documentation Error in README.md

### ISSUE THREAD

**Issue by jmknoll** [gillyb/reimg#1]
Last line of the readme, in usage examples. Currently reads:

// convert canvas to png
var png = ReImg.fromSvg(document.getElementByID('canvasId')).toPng();

Should be changed to: 

ReImg.**fromCanvas**(document.getElementByID('canvasId')).toPng();

**Comment by lisajamhoury** [comment]
There's still an error here. ID should be Id, not all caps. It's getElementById, not getElementByID as written in the readme.

**Comment by gillyb** [comment]
damn! you're right! thanks a lot for pointing that out :)
