### ISSUE TITLE
Suggestion (without pull request): Add optional filename parameter to downloadPng.

### ISSUE THREAD

**Issue by Neofish22** [gillyb/reimg#3]
Noticed one could readily implement user-specification of the filename for a download. You could of course implement this however best suits your style. I don't want to submit a pull request because of the relative simplicity of the change.

Relatively small changes:
- Add a filename parameter to downloadPng,
- Add default for that filename.
- Replace occurrences of 'image.png' with filename.

downloadPng becomes:

```
downloadPng: function(filename) {
    filename = filename || 'image.png';
    if (isPng()) {
        // it's a canvas already
        downloadImage(encodedData, filename);
        return;
    }

    // convert to canvas first
    this.toCanvas(function(canvas) {
        downloadImage(canvas.toDataURL(), filename);
    });
}
```

I do really like the lib, though, thanks. :)

**Comment by gillyb** [comment]
ok, i'll make the change. Thanks for the note! :)
and i'm happy to hear you enjoy it!
