### ISSUE TITLE
SecurityError issue

### ISSUE THREAD

**Issue by Sarabpreet** [gillyb/reimg#4]
## just checked this plugin, its throwing me this error, could you help?

![screen shot 2016-02-26 at 2 49 30 pm](https://cloud.githubusercontent.com/assets/4095517/13348216/31f8f7ae-dc98-11e5-99d3-7fad47e0045a.png)

**Comment by gillyb** [comment]
This error usually appears when you try to save an image coming from another domain...
Could this be the situation here ?

btw - which browser are u using ?

**Comment by Sarabpreet** [comment]
Perhaps!,
i have an image coming from facebook api,  and another one from localhost, combining the two into #myCanvas  element, and then trying to save via reimg. Will it be an issue?  Is there anything we can do about it? 

i am using Firefox. :smile:

**Comment by gillyb** [comment]
do you have a server side to your project ?
If so, the best solution would be to create an endpoint that will just act as a proxy, and then get the image from the endpoint on your server, so the browser thinks it's "your" image...

**Comment by gillyb** [comment]
Not getting any response on this, and not sure if there's something else I can do, so I'm closing this for now...
