### ISSUE TITLE
Publish reimg as npm package

### ISSUE THREAD

**Issue by mslawins** [gillyb/reimg#9]
Could you publish reimg as npm package?

**Comment by pcnate** [comment]
PR #10 is meant to start addressing this issue

**Comment by gillyb** [comment]
@mslawins @pcnate Sorry for being so late to do this. Honestly I didn't realise there were issues on this repo. I published it now if this still helps.
https://www.npmjs.com/package/reimg

**Comment by pcnate** [comment]
Awesome. Thank you!
